version: '3'
services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
  db:
    image: postgres:latest
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
volumes:
  postgres_data:
