version: "3"
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: rails server -b 0.0.0.0 -p 3000
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
